"""Git worktree lifecycle and host-side publishing transport."""

from __future__ import annotations

import hashlib
import os
import re
import stat
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path


class GitError(RuntimeError):
    pass


@dataclass(slots=True)
class Worktree:
    repo_root: Path
    path: Path
    branch: str
    base_ref: str
    base_sha: str


class WorktreeManager:
    def __init__(self, state_root: Path):
        self.root = state_root.resolve() / "worktrees"
        self.root.mkdir(parents=True, exist_ok=True)

    def inspect_repo(self, repo_path: Path) -> Path:
        candidate = repo_path.resolve()
        output = _git(candidate, ["rev-parse", "--show-toplevel"])
        root = Path(output.strip()).resolve()
        if not (root / ".git").exists() and not (root / ".git").is_file():
            raise GitError(f"Not a Git worktree: {root}")
        return root

    def create(
        self,
        *,
        repo_path: Path,
        repo_slug: str,
        issue_number: int,
        run_id: str,
        default_branch: str = "main",
        base_ref: str = "",
    ) -> Worktree:
        repo_root = self.inspect_repo(repo_path)
        safe_repo = re.sub(r"[^A-Za-z0-9_.-]", "_", repo_slug)
        destination = (self.root / safe_repo / run_id).resolve()
        destination.parent.mkdir(parents=True, exist_ok=True)
        if destination.exists():
            raise GitError(f"Worktree path already exists: {destination}")
        selected_base = base_ref or self._select_base(repo_root, default_branch)
        base_sha = _git(repo_root, ["rev-parse", selected_base]).strip()
        branch = f"gha/issue-{issue_number}-{run_id.removeprefix('run_')}"
        _git(
            repo_root,
            ["worktree", "add", "-b", branch, str(destination), selected_base],
        )
        return Worktree(repo_root, destination, branch, selected_base, base_sha)

    def recover(self, run: dict) -> Worktree:
        path = Path(run["worktree_path"]).resolve()
        if not path.is_dir():
            raise GitError(f"Saved worktree no longer exists: {path}")
        repo_root = self.inspect_repo(Path(run["repo_path"]))
        actual_branch = _git(path, ["branch", "--show-current"]).strip()
        if actual_branch != run["branch"]:
            raise GitError(
                f"Worktree branch changed: expected {run['branch']}, got {actual_branch}"
            )
        return Worktree(repo_root, path, run["branch"], run["base_ref"], run["base_sha"])

    def _select_base(self, repo_root: Path, default_branch: str) -> str:
        remote = f"origin/{default_branch}"
        try:
            _git(repo_root, ["rev-parse", "--verify", remote])
            return remote
        except GitError:
            return "HEAD"


def git_status(worktree: Path) -> str:
    return _git(worktree, ["status", "--short"]) or "(clean)"


def changed_files(worktree: Path) -> list[str]:
    """Return tracked edits and untracked files without parsing porcelain status prefixes."""
    tracked = _git(worktree, ["diff", "--name-only", "--no-ext-diff", "HEAD"])
    untracked = _git(worktree, ["ls-files", "--others", "--exclude-standard"])
    return sorted(set(tracked.splitlines() + untracked.splitlines()) - {""})


def git_diff(worktree: Path, *, max_chars: int = 80_000) -> str:
    tracked = _git(worktree, ["diff", "--no-ext-diff", "--binary", "HEAD"])
    untracked = _git(worktree, ["ls-files", "--others", "--exclude-standard"]).splitlines()
    parts = [tracked]
    for relative in untracked:
        path = (worktree / relative).resolve()
        try:
            path.relative_to(worktree.resolve())
        except ValueError:
            continue
        if path.is_file():
            try:
                content = path.read_text(encoding="utf-8")
            except (UnicodeDecodeError, OSError):
                content = "[binary or unreadable file]"
            parts.append(f"\n--- /dev/null\n+++ b/{relative}\n{content}")
    result = "\n".join(parts).strip() or "(no changes)"
    if len(result) > max_chars:
        return result[:max_chars] + f"\n[diff truncated {len(result) - max_chars} chars]"
    return result


def snapshot_hash(worktree: Path) -> str:
    status = git_status(worktree)
    diff = git_diff(worktree, max_chars=10_000_000)
    return hashlib.sha256(f"{status}\n{diff}".encode("utf-8")).hexdigest()


def current_head(worktree: Path) -> str:
    return _git(worktree, ["rev-parse", "HEAD"]).strip()


def commit_changes(worktree: Path, *, issue_number: int, run_id: str) -> str:
    if git_status(worktree) == "(clean)":
        raise GitError("Cannot commit: worktree has no changes")
    _git(worktree, ["add", "-A"])
    message = f"fix: resolve issue #{issue_number}\n\nGenerated by gh-assistant run {run_id}."
    _git(
        worktree,
        [
            "-c",
            "core.hooksPath=" + os.devnull,
            "-c",
            "user.name=gh-assistant",
            "-c",
            "user.email=gh-assistant@users.noreply.github.com",
            "commit",
            "-m",
            message,
        ],
    )
    return _git(worktree, ["rev-parse", "HEAD"]).strip()


def push_branch(
    worktree: Path,
    *,
    repo_slug: str,
    branch: str,
    github_token: str,
) -> str:
    if not github_token:
        raise GitError("GITHUB_TOKEN is required to push")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repo_slug):
        raise GitError(f"Invalid GitHub repository slug: {repo_slug}")
    remote = f"https://github.com/{repo_slug}.git"
    with tempfile.TemporaryDirectory(prefix="gha-askpass-") as tmp:
        script = _write_askpass(Path(tmp))
        env = _git_env()
        env.update(
            {
                "GIT_ASKPASS": str(script),
                "GIT_ASKPASS_REQUIRE": "force",
                "GIT_TERMINAL_PROMPT": "0",
                "GHA_GIT_TOKEN": github_token,
            }
        )
        _run_git(
            worktree,
            [
                "-c",
                "core.hooksPath=" + os.devnull,
                "-c",
                "credential.helper=",
                "push",
                remote,
                f"HEAD:refs/heads/{branch}",
            ],
            env=env,
        )
    return branch


def _write_askpass(directory: Path) -> Path:
    helper = directory / "askpass.py"
    helper.write_text(
        "import os, sys\n"
        "prompt = sys.argv[1].lower() if len(sys.argv) > 1 else ''\n"
        "print('x-access-token' if 'username' in prompt else os.environ['GHA_GIT_TOKEN'])\n",
        encoding="utf-8",
    )
    if os.name == "nt":
        wrapper = directory / "askpass.cmd"
        wrapper.write_text(
            f'@"{sys.executable}" "{helper}" %*\n', encoding="utf-8"
        )
        return wrapper
    helper.write_text("#!/usr/bin/env python3\n" + helper.read_text(encoding="utf-8"), encoding="utf-8")
    helper.chmod(helper.stat().st_mode | stat.S_IXUSR)
    return helper


def _git(cwd: Path, args: list[str]) -> str:
    return _run_git(cwd, args, env=_git_env())


def _run_git(cwd: Path, args: list[str], *, env: dict[str, str]) -> str:
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=cwd,
            env=env,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=120,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise GitError(f"git {' '.join(args)} failed to start: {exc}") from exc
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        raise GitError(f"git {' '.join(args)} failed: {detail}")
    return result.stdout.strip()


def _git_env() -> dict[str, str]:
    keys = {"PATH", "SYSTEMROOT", "WINDIR", "TEMP", "TMP", "HOME", "USERPROFILE"}
    env = {key: value for key, value in os.environ.items() if key.upper() in keys}
    env["GIT_CONFIG_NOSYSTEM"] = "1"
    env["GIT_OPTIONAL_LOCKS"] = "0"
    return env
